### ISSUE TITLE
Main search function

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#10]
Needs to call query parser and then ranker and returns a sorted list

search(searchstring, dictionary_directory)

**Comment by moritzschaefer** [comment]
check branch feature/searchinterface

**Comment by moritzschaefer** [comment]
Please checkout and implement it :)

**Comment by brianignacio5** [comment]
Rank function and test implemented. Please check comments in search.py

**Comment by moritzschaefer** [comment]
IMPORTANT: Use the dictionary.dat path as index_directory parameter
    until the dictionary hash logic is defined.

The dictionary hash logic is implemented and merged already in master. 

    # TODO Modify get_dictionary_term_list in tsg.ranker.base to 
    # use the hash dictionary and read a position in dictionary 
    # instead of line by line

Haha, why would you place this comment in search.py??? Rather make a github issue
