### ISSUE TITLE
Page Rank 

### ISSUE THREAD

**Issue by brianignacio5** [moritzschaefer/the-search-engine#12]
Guess who?

1. [x] Make the documentation of how you would implement it. Be real bro.
2. [x] Make some red tests to have idea of working functionality.
3. [x] Make some functions to get the thing rolling.
4. [x] Green tests and put it to work.
5. [x] Get links from documents (in parser, use something like this: //a/@href, filter links to point to the trier-db only!
6. [x] Change use of uuid.uuid4() to name parsed documents! use raw filename for uuid instead. example journal_ai_ai99.html uuid=uuid=journal_ai_ai99, parsed_filename=uuid=journal_ai_ai99.json

**Comment by moritzschaefer** [comment]
haha thanks for self assigning. this goes for milestone 2 ;)

**Comment by moritzschaefer** [comment]
Following thoughts on this:


# Making the importancy dict (or how did you call it?)
doc_dict = {}
for doc in RAW_DIR/*.html:
    for link in doc:
        target_doc = parse_link(link) # http://blabla/author/w/william:lala -> w_william_lala
        if target_doc is in [author, journal, conference]:
            doc_dict[target_doc].append(doc) # append to a list. in the end we know for every doc, which docs are pointing to it. 

# After that we can iterate again over all files and check for the docs that point to it, seeing if they are important

pagerank_score = DefaultDict(0)
for doc in RAW_DIR/*.html:
    for referencing_doc in doc_dict[doc]:
        pagerank_score[doc] += len(doc_dict[referencing_doc])

**Comment by brianignacio5** [comment]
Makes perfect sense. Two only things i'll modify would be that for each doc i'll create a xpath tree and get the list of links  and the inner loop would use each link in this list. Another thing is: how to get the doc_id based on the link? the parse doc function should do a mapping between the url link and the document id in our index.

**Comment by moritzschaefer** [comment]
well we use the same method as used in the parser to get the filename. One
thing to consider: We use UUIDs later, not the filename anymore. Maybe we
will have to change something there, to make the relation work..

Brian A. Ignacio <notifications@github.com> schrieb am Sa., 9. Apr. 2016 um
14:51 Uhr:

**Comment by moritzschaefer** [comment]
I NDEXING ANCHOR TEXT

When indexing a document D, include (with some
weight) anchor text from links pointing to D.

**Comment by brianignacio5** [comment]
Can we close this? @moritzschaefer

**Comment by moritzschaefer** [comment]
Yes

Brian A. Ignacio <notifications@github.com> schrieb am Do., 5. Mai 2016,
11:30:
