### ISSUE TITLE
Tests are slow

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#13]
Hey,

tests are too slow. please speed them up (i.e. don't download so much stuff!). 

Tests should run in < 2 seconds.

**Comment by brianignacio5** [comment]
test_ranker runs in 0.331s so it's ok. Do you want to remove the crawling tests  in test_crawler?

**Comment by moritzschaefer** [comment]
Then we have to improve there too... You know which tests are slow?

**Comment by brianignacio5** [comment]
All of them hahaha. Because crawl_urls in tsg.crawler.base need to download a webpage and saves the 300 (authors) or 100 (journals or conferences) links. crawl_journal_url does the same but involves less links to save (just  4 in the test) although still crawl the site.

**Comment by moritzschaefer** [comment]
In fact we can change that by mocking the requests call:
http://stackoverflow.com/questions/15753390/python-mock-requests-and-the-response
Though, I'm too lazy to do that right now, though this is the way to go! Keep the file offline and mock the get-call to return the contents of the offline-stored test-html-file.
Let's keep the issue open and fix it some time together.. :)

**Comment by moritzschaefer** [comment]
Ok , let's just ignore it :)

**Comment by brianignacio5** [comment]
Would be nice so i can practice mocking, but this is something to do when we finish a working release.
