### ISSUE TITLE
Fix ranker test

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#14]
moritz@mobook ~/tsg (master) $ nosetests
.............F.
======================================================================
FAIL: test.test_ranker.test_term_query_weight
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/moritz/Seafile/Meine Bibliothek/Studium/websearch/project/test/test_ranker.py", line 41, in test_term_query_weight
    assert round(term_weight,4) == round(weight,4)
AssertionError

----------------------------------------------------------------------
Ran 15 tests in 34.591s

FAILED (failures=1)

**Comment by brianignacio5** [comment]
This is semi fixed. We need the numbers of docs in our index for query_term_weight function in tsg/ranker/base.py

**Comment by brianignacio5** [comment]
Fixed using N = len(glob.glob(RAW_DIR+'*.html'))

**Comment by brianignacio5** [comment]
Please review N is now being read from dictionary. Please add the line "num_documents 25813" in your test dictionary

**Comment by moritzschaefer** [comment]
revert revert! :). Run this (in the branch you made the comment doing this N-thing):

git revert 76bc8c5 
76bc8c5 is the commit-hash for the commit where you did that stuff.

This creates another commit reverting your changes in that commit.

Is that ok? :)

**Comment by brianignacio5** [comment]
Can we close this ?

**Comment by moritzschaefer** [comment]
Please

Brian A. Ignacio <notifications@github.com> schrieb am So., 10. Apr. 2016,
15:17:
