### ISSUE TITLE
Finalize Milestone 1

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#17]
Milestone 1 is almost ready. Only a bit of glue is missing:

Check out branch 'feature/searchinterface' and complete the code in tsg/search.py

**Comment by brianignacio5** [comment]
Please review last commit on 'feature/searchinterface' branch. Merge with the bug fix in master (N calculation fix in ranker)

**Comment by brianignacio5** [comment]
@moritzschaefer Please update "'feature/searchinterface" with new changes in master.

**Comment by moritzschaefer** [comment]
rebase-master-in-searchinterface.
function 'rank' is missing in there.. could you fix that? :)

**Comment by brianignacio5** [comment]
Fixed. Should we close this issue?

**Comment by moritzschaefer** [comment]
No. It has to seen working first :).
You are welcome to do a test search!

Brian A. Ignacio <notifications@github.com> schrieb am So., 10. Apr. 2016,
18:55:

**Comment by moritzschaefer** [comment]
moritz@mobook ~/tsg/bin (master) $ ./tsg_rank hell hello
[('1ae71d9e-bb63-4035-b5c7-947f0d2db1ab', 1.0)]

We want this not to be ranked, right??

**Comment by brianignacio5** [comment]
Is a very strange behaviour. The term hell and/or hello only has this document ? Is there a term that doesn't exist in the dictionary? If one term doesn't exist in the dictionary and the other term just have this document, then the ranking is working fine.

**Comment by moritzschaefer** [comment]
Hell exists. Hello not....
I expect the query "hell hello"  to return an empty list.
We could implement a feature to combine terms conjunctive and disjunctive.
Like in google  using OR...

Brian A. Ignacio <notifications@github.com> schrieb am Sa., 16. Apr. 2016,
18:28:

**Comment by brianignacio5** [comment]
I think it should return something. Even though you search for hell hello, and you only can supply for hell, your user expects some results, at least partially. So i think the behavior is ok. Because what we actually do is to find those documents closer to the query. If you want a perfect match only, then the approach is more binary and less cosine similarity.

**Comment by moritzschaefer** [comment]
That's not true as is! It's not about binary and not binary!
Look at Google! If you type in too many words you'll end up with 0
results. Nowadays most IR systems word disjunctive not conjunctive!! (as
well said in the lecture).  I think it's best if we implement and provide
both ways, but default should be, what is the normal/standard today.

Brian A. Ignacio <notifications@github.com> schrieb am So., 17. Apr. 2016,
16:24:
