### ISSUE TITLE
Fix Journal Crawling

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#2]
Clicking on an item in
http://dblp.uni-trier.de/db/journals/?prefix=A
doesn't lead to the desired page of the journal but to a selection page for the Volume(http://dblp.uni-trier.de/db/journals/csur/)
We need one more function to "open" all these Volumes and crawl the data in there. Maybe we can add a new field "volume" later?

**Comment by brianignacio5** [comment]
Already defined 2 functions crawl_journal_url(journal_url) and crawl_journal_subsites(journal_url). The first returns a list which contains the info site in the journal site (firsts links) and a second list with volume sites. The 2nd function uses the 1st function to get URLS in a list of lists, and uses a loop to crawl each volume site. *Please check the crawl_site() function to validate if this volumes URL can be crawl well* I think i can make an assert with a volume url in the test_crawl_site() function, but i wanted to asked first without modify it .
