### ISSUE TITLE
Implement hash to improve fast dictionary search

### ISSUE THREAD

**Issue by brianignacio5** [moritzschaefer/the-search-engine#21]
1. [x] Implement hash of dictionary with term position to improve dictionary reading.
2. [x] Modify tsg.ranker.get_dictionary_term_list to use the dictionary hash to find the term position in file faster.

**Comment by moritzschaefer** [comment]
Point one is done already (or am I confusing?)
Check twst/test_hasher.py

Brian A. Ignacio <notifications@github.com> schrieb am So., 10. Apr. 2016,
19:02:

**Comment by moritzschaefer** [comment]
https://github.com/moritzschaefer/the-search-engine/pull/22
integrated. please click merge :) 
BTW the naming of term_list and get_dictionary_term_list is vveeeryy missleading as it is a list of documents and not a list of terms (or do I see something wrong?)

**Comment by brianignacio5** [comment]
You can rename for what you want. The list refers to the documents list for a given term. Something like term_documents_list ?

Code seems about right. If tests runs OK then please merge.

**Comment by moritzschaefer** [comment]
Haha you can click the button :)
Yeah, that suggested name sounds better. But you don't have to change it.
Was just something I stumbled upon.

Brian A. Ignacio <notifications@github.com> schrieb am Sa., 16. Apr. 2016,
17:34:
