### ISSUE TITLE
High weight on title, isbn and category!

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#25]
As planned boost the tf-idf of these maybe in the intermediate step..

**Comment by brianignacio5** [comment]
Some thoughts about this.

The ranker returns a list of documents based (until now) in cosine similarity. An added scoring criteria would take this list of documents, check the corresponding JSON for the given doc_id and checks if the terms in the given query appears in one of title, ISBN and category fields. 
Remarks: Is the additional scoring a number between 0 and 1, or is it an integer like 1 that is added to previous scoring methods?

**Comment by moritzschaefer** [comment]
Too complicated! For a long list of matched documents we have to open and
Json parse each file....
I think I already put in the readme a more effective idea:
While computing the intermediate files we know where a term comes from. If
it's from title-field we just multiply the number of occurrences of the
given term by 2(or so).
That's super simple and effective!

Brian A. Ignacio <notifications@github.com> schrieb am Sa., 16. Apr. 2016,
17:42:

**Comment by moritzschaefer** [comment]
https://github.com/moritzschaefer/the-search-engine/pull/32
