### ISSUE TITLE
 Free text query checker

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#28]
Free text query checker: Check if returned documents are lower than K docs, try different substrings combination of inserted query.

**Comment by brianignacio5** [comment]
Comment: Use disjunctive if less than K docs use conjunctive approach?

**Comment by moritzschaefer** [comment]
The question is, if it is "enough" for the Professor. Does it fit with the requirements?

**Comment by brianignacio5** [comment]
It doesn't really specify too much on requirements.  It just says to include free text query checker. I think we can implement  and search, check for a minimum numbers of results, if less then combine with or search, if still less than minimum numbers of results then repeat and or searches until > min numbers of results.

**Comment by moritzschaefer** [comment]
perfect! then this one is as good as done. let's implement it as soon as
the rest is running.

Brian A. Ignacio <notifications@github.com> schrieb am So., 24. Apr. 2016
um 16:12 Uhr:
