### ISSUE TITLE
Bug in page_rank.py

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#37]
if "pers" in doc_link:
        category = "author"
    elif "conf" in doc_link:
        category = "conference"
    elif "journals" in doc_link:
        category = "journal"
    else:
        category = ""

if a person is called "confucius" he gets categorized as a conferences! fix this. 

And never copy code. A better approach would have been to extract a function from crawler/base.py for getting the file name from a url and use this function in both, the old code (crawler/base) and the your new code page_rank

**Comment by brianignacio5** [comment]
Please refer to commit e8e9c79ab80e87e4e0caf04f7fa1d5640e5ab977 in master for a possible solution. About the code, if you look closely, it's not exactly the same as the code from crawler/base.py. If it were the same, i would just reference the original as you say.

**Comment by moritzschaefer** [comment]
This is good enough :).

Hmm still some code copied :P (I copy code too, no worries)
