### ISSUE TITLE
Response testing

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#42]
This issue is to work out a protocol on how to test the outcome of the search engine. Especially, we want to have a good precission (on the first items). 

PLEASE MAKE YOUR OWN THOUGHTS ON HOW TO TEST IF THE OUTCOME OF THE RANKER IS "GOOD".

Here my thoughts:

- For a few random people, search for their name should return their author-page as the highest ranked document.
- Same for conferences and journals.
- ISBN search should work. 
- looking for some journals should bring as to the conference that hosted them. (or vice versa?)

**Comment by brianignacio5** [comment]
I agree your thoughts. I believe there should be like 1st degree result: like title match, then 2nd second degree that is content match and 3rd degree that is close relation match (this should be some OR result).

**Comment by brianignacio5** [comment]
So how did you find the results? Everything working ok? I will start documenting this weekend, hopefully everything is alright.

@moritzschaefer Please let me know if anything i can/need to do.

@NMickhy Finish your part already.
