### ISSUE TITLE
optimize ranker/base.py

### ISSUE THREAD

**Issue by moritzschaefer** [moritzschaefer/the-search-engine#43]
def calculate_query_term_weight(term, query_terms, index_dictionary_path=DICTIONARY_PATH,
    index_info_path = INDEXINFO_PATH):
    term_dictionary = get_dictionary_term_list(term, index_dictionary_path)

calculate_query_term_weight shouldn't call get_dictionary_term_list. The functions using calculate_query_term_weight also call that function. This can be expensive for terms with many documents. please fix by passing the dictionary term list as a parametr to the calculate_query_term_weight function. 

adapt the tests

**Comment by brianignacio5** [comment]
Please review https://github.com/moritzschaefer/the-search-engine/pull/44

**Comment by brianignacio5** [comment]
Can we close this ?
