### ISSUE TITLE
Ranker initial definition

### ISSUE THREAD

**Issue by brianignacio5** [moritzschaefer/the-search-engine#5]
1. [x] Term-Document List Extractor: Check the indexer file and extract the list from each term.
2. [x] Cosine score calculation: Function to calculate product of tf-idf from query and document and normalize them. (See Ranker doc)
3. [x] Term-document list merger (Take each term-document list, use cosine score calculation to measure document list.) Early definition not sure entirely.

**Comment by moritzschaefer** [comment]
@brianignacio5 
Term-document list merger (Take each term-document list (cosine scores already computed) and combine them).
Example.
query: "a b".
a finds these documents in index with cosine scores being calculated: (doc1:1.1, doc2:1.3)
b finds these documents: (doc1:3.5)
merged, this is the final result list:
(doc1:1.1*3.5,doc2:1.3*0). doc2 results in weight 0 and will not appear in results list...

好吗？ :)

**Comment by brianignacio5** [comment]
@moritzschaefer  If you see cosine_score_calc function you can observe that the returned object is a dictionary {doc_id : score} so the output already merges the docs lists.

**Comment by moritzschaefer** [comment]
@brianignacio5  Can we close this?
